---
title: "Resources"
---

## R

-   [CS50 R](https://cs50.harvard.edu/r/) *Course*
-   [R for Data Science](https://r4ds.hadley.nz/) *Book*
-   [Data Visualization: A Practical Introduction](https://socviz.co/) *Book*
-   [Advanced R](https://adv-r.hadley.nz/) *Book*

## Python

-   [CS50 Python](https://cs50.harvard.edu/python/) *Course*
-   [ThinkPython](https://allendowney.github.io/ThinkPython/) *Book*
-   [Python Data Science Hanbook](https://jakevdp.github.io/PythonDataScienceHandbook/) *Book*
-   [Python for Data Analysis](https://wesmckinney.com/book/) *Book*

## Machine Learning

-   [An Introduction to Statistical Learning](https://www.statlearning.com/) *Book*
-   [StatQuest with Josh Starmer](https://www.youtube.com/c/joshstarmer) *YouTube Channel*
-   [FastAI: Practical Deep Learning](https://course.fast.ai/) *Course*
-   [Dive into Deep Learning](https://d2l.ai/) *Book*

## Git

-   [Git and Github for Poets](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV) *YouTube Playlist*
-   [Pro Git](https://git-scm.com/book/en/v2) *Book*

## Web Development

-   [freeCodeCamp](https://git-scm.com/book/en/v2) *Curriculum*
-   [The Odin Project](https://www.theodinproject.com/) *Curriculum*
-   [CS50 Web](https://cs50.harvard.edu/web/) *Course*

## Other Programming Resources

-   [Modern Plain Text Computing](https://mptc.io/) *Course*
-   [CS50x](https://cs50.harvard.edu/x/) *Course*
-   [LinuxCommand.org](https://linuxcommand.org/) *Website*

## Statistics & Econometrics

-   [OpenIntro Statistics](https://leanpub.com/os) *Book*
-   [Introduction to Modern Statistics](https://openintrostat.github.io/ims/) *Book*
-   [Regression and Other Stories](https://avehtari.github.io/ROS-Examples/) *Book*
-   [StatQuest with Josh Starmer](https://www.youtube.com/c/joshstarmer) *YouTube Channel*

## Causal Inference

-   [The Effect: An Introduction to Research Design and Causality](https://theeffectbook.net/) *Book*
-   [Causal Inference: The Mixtape](https://mixtape.scunning.com/) *Book*
-   [Causal ML](https://causalml-book.org/) *Book*
